set(FoundationClasses TKernel TKMath)

set(ModelingData TKG2d TKG3d TKGeomBase TKBRep)

set(ModelingAlgorithms TKGeomAlgo TKTopAlgo TKPrim TKBO TKBool TKHLR TKFillet TKOffset TKFeat TKMesh TKXMesh TKShHealing)

set(Visualization TKService TKV3d TKOpenGl TKOpenGles TKMeshVS TKIVtk TKD3DHost)

set(ApplicationFramework TKCDF TKLCAF TKCAF TKBinL TKXmlL TKBin TKXml TKStdL TKStd TKTObj TKBinTObj TKXmlTObj TKVCAF)

set(DataExchange TKXSBase TKSTEPBase TKSTEPAttr TKSTEP209 TKSTEP TKIGES TKXCAF TKXDEIGES TKXDESTEP TKSTL TKVRML TKXmlXCAF TKBinXCAF TKRWMesh)

set(TKernel FSD OSD Plugin Quantity Resource Standard StdFail Storage TColStd TCollection TShort Units UnitsAPI UnitsMethods NCollection Message)
set(TKMath math ElCLib ElSLib BSplCLib BSplSLib PLib Precision GeomAbs Poly CSLib Convert Bnd BVH gp TColgp TopLoc Expr ExprIntrp)
set(TKG2d Geom2d LProp TColGeom2d Adaptor2d Geom2dLProp Geom2dAdaptor Geom2dEvaluator)
set(TKG3d Geom TColGeom GeomAdaptor AdvApprox GeomLProp Adaptor3d LProp3d TopAbs GeomEvaluator GProp)
set(TKGeomBase ProjLib GeomProjLib GCPnts CPnts Approx AppParCurves FEmTool AppCont Extrema IntAna IntAna2d GeomConvert AdvApp2Var GeomLib Geom2dConvert Hermit BndLib AppDef GeomTools GC GCE2d gce)
set(TKBRep TopoDS TopExp TopTools BRep BRepLProp BRepAdaptor BRepTools BinTools)
set(TKGeomAlgo Hatch GeomInt IntStart IntWalk IntImp IntCurveSurface IntSurf IntPatch Geom2dInt IntImpParGen IntRes2d IntCurve TopTrans Intf ApproxInt GccAna GccEnt GccInt HatchGen Geom2dHatch Law AppBlend Plate GeomPlate LocalAnalysis GeomAPI GeomFill Geom2dAPI Geom2dGcc FairCurve NLPlate IntPolyh TopClass)
set(TKTopAlgo IntCurvesFace MAT MAT2d Bisector BRepMAT2d BRepCheck BRepBndLib BRepExtrema BRepClass BRepClass3d BRepLib BRepGProp BRepIntCurveSurface BRepTopAdaptor BRepBuilderAPI BRepApprox)
set(TKPrim BRepPrim BRepSweep Sweep BRepPreviewAPI BRepPrimAPI)
set(TKBO IntTools BRepAlgoAPI BOPDS BOPAlgo BOPTools)
set(TKBool TopOpeBRep TopOpeBRepDS TopOpeBRepBuild TopOpeBRepTool BRepAlgo BRepFill BRepProj)
set(TKHLR HLRTopoBRep HLRBRep HLRAlgo HLRAppli Intrv TopBas TopCnx Contap)
set(TKFillet ChFiDS ChFi2d ChFi3d ChFiKPart Blend BRepBlend BlendFunc BRepFilletAPI FilletSurf)
set(TKOffset BRepOffsetAPI Draft BRepOffset BiTgte)
set(TKFeat LocOpe BRepFeat)
set(TKMesh IMeshData IMeshTools BRepMeshData BRepMesh)
set(TKXMesh XBRepMesh)
set(TKShHealing ShapeBuild ShapeExtend ShapeConstruct ShapeCustom ShapeAnalysis ShapeFix ShapeUpgrade ShapeAlgo ShapeProcess ShapeProcessAPI)
set(TKService Aspect Graphic3d Xw Image Media Wasm WNT Cocoa Font)
set(TKV3d V3d Select3D Prs3d StdPrs SelectBasics SelectMgr PrsMgr AIS StdSelect DsgPrs PrsDim)
set(TKOpenGl OpenGl)
set(TKOpenGles OpenGl)
set(TKMeshVS MeshVS)
set(TKIVtk IVtk IVtkOCC IVtkVTK IVtkTools)
set(TKD3DHost D3DHost)
set(TKCDF CDM PCDM CDF UTL LDOM)
set(TKLCAF TDF TDataStd TFunction TDocStd AppStdL)
set(TKCAF TDataXtd TNaming AppStd)
set(TKBinL BinMDF BinMDataStd BinMFunction BinMDocStd BinObjMgt BinLDrivers)
set(TKXmlL XmlLDrivers XmlMDF XmlMDataStd XmlMDocStd XmlMFunction XmlObjMgt)
set(TKBin BinDrivers BinMDataXtd BinMNaming)
set(TKXml XmlDrivers XmlMDataXtd XmlMNaming)
set(TKStdL StdLDrivers StdLPersistent StdObjMgt)
set(TKStd StdDrivers StdObject StdPersistent StdStorage ShapePersistent)
set(TKTObj TObj)
set(TKBinTObj BinTObjDrivers)
set(TKXmlTObj XmlTObjDrivers)
set(TKVCAF TPrsStd)
set(TKXSBase Interface Transfer IFGraph IFSelect TransferBRep XSControl StepData StepFile HeaderSection RWHeaderSection APIHeaderSection StepSelect XSAlgo LibCtl MoniTool)
set(TKSTEPBase StepBasic RWStepBasic StepRepr RWStepRepr StepGeom RWStepGeom StepShape RWStepShape)
set(TKSTEPAttr StepVisual RWStepVisual StepDimTol RWStepDimTol StepKinematics RWStepKinematics)
set(TKSTEP209 StepElement StepFEA RWStepElement RWStepFEA)
set(TKSTEP StepAP214 RWStepAP214 StepAP203 RWStepAP203 STEPConstruct STEPEdit GeomToStep StepToGeom StepToTopoDS TopoDSToStep STEPControl STEPSelections StepAP209 RWStepAP242 StepAP242)
set(TKIGES IGESData IGESFile IGESBasic IGESGraph IGESGeom IGESDimen IGESDraw IGESSolid IGESDefs IGESAppli IGESConvGeom IGESSelect IGESToBRep GeomToIGES Geom2dToIGES BRepToIGES BRepToIGESBRep IGESControl)
set(TKXCAF XCAFApp XCAFDimTolObjects XCAFNoteObjects XCAFDoc XCAFPrs XCAFView)
set(TKXDEIGES IGESCAFControl)
set(TKXDESTEP STEPCAFControl)
set(TKSTL StlAPI RWStl)
set(TKVRML VrmlConverter VrmlAPI Vrml VrmlData)
set(TKXmlXCAF XmlXCAFDrivers XmlMXCAFDoc)
set(TKBinXCAF BinXCAFDrivers BinMXCAFDoc)
set(TKRWMesh RWGltf RWMesh RWObj)